apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: python:3.11-slim
          command: ["sh", "-c"]
          args: ["pip install flask redis && python /app/formulario.py"]
          env:
            - name: FLASK_APP
              value: "formulario.py" # nome do seu arquivo Flask
            - name: FLASK_ENV
              value: "development"
            - name: REDIS_IP
              value: "${REDIS_IP}"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: app-code
              mountPath: /app
      volumes:
        - name: app-code
          configMap:
            name: flask-app-code
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
